export const ENDPOINTS = {
  HEALTH: '/health',
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  BUSINESS_STATUS_TODAY: '/business/status/today',
  MENU_TODAY: '/menu/today',
  MENU_ITEM_AVAILABILITY: (id) => `/menu/today/items/${id}/availability`,
  ADMIN_DISHES: '/admin/dishes',
  ADMIN_DISH: (id) => `/admin/dishes/${id}`,
  ADMIN_DASHBOARD_SUMMARY: '/admin/dashboard/summary',
  ADMIN_DASHBOARD_TOP_DISHES: '/admin/dashboard/top-dishes',
  ADMIN_MANUAL_SALES: '/admin/sales/manual',
  ADMIN_WEEKLY_REPORT_SUMMARY: '/admin/reports/weekly/summary',
  ADMIN_WEEKLY_REPORT_PDF: '/admin/reports/weekly/pdf',
  CART: '/cart',
  CART_ITEMS: '/cart/items',
  CART_ITEM: (id) => `/cart/items/${id}`,
  CART_CHECKOUT: '/cart/checkout',
  MY_ORDERS: '/orders/my',
  MY_ORDER: (id) => `/orders/my/${id}`,
  NOTIFICATIONS: '/notifications',
  NOTIFICATION_READ: (id) => `/notifications/${id}/read`,
  NOTIFICATIONS_READ_ALL: '/notifications/read-all',
  ME: '/me',
};
