export const ENDPOINTS = {
  HEALTH: '/health',
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  BUSINESS_STATUS_TODAY: '/business/status/today',
  BUSINESS_CONFIGURATION: '/business/configuration',
  BUSINESS_CONFIGURATION_LOGO: '/business/configuration/logo',
  MENU_TODAY: '/menu/today',
  MENU_ITEM_AVAILABILITY: (menuItemId) => `/menu/today/items/${menuItemId}/availability`,
  CART: '/cart',
  CART_ITEMS: '/cart/items',
  CART_ITEM: (itemId) => `/cart/items/${itemId}`,
  CART_CHECKOUT: '/cart/checkout',
  MY_ORDERS: '/orders/my',
  MY_ORDER: (orderId) => `/orders/my/${orderId}`,
  NOTIFICATIONS: '/notifications',
  NOTIFICATION_READ: (notificationId) => `/notifications/${notificationId}/read`,
  NOTIFICATIONS_READ_ALL: '/notifications/read-all',
  ME: '/me',
  ADMIN_BUSINESS_CONFIGURATION: '/admin/business/configuration',
  ADMIN_BUSINESS_CONFIGURATION_LOGO: '/admin/business/configuration/logo',
  ADMIN_DISHES: '/admin/dishes',
  ADMIN_DISH: (dishId) => `/admin/dishes/${dishId}`,
  ADMIN_DISH_IMAGE: (dishId) => `/admin/dishes/${dishId}/image`,
  ADMIN_DASHBOARD_TODAY: '/admin/dashboard/today',
  ADMIN_DASHBOARD_SUMMARY: '/admin/dashboard/summary',
  ADMIN_DASHBOARD_TOP_DISHES: '/admin/dashboard/top-dishes',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_ORDER: (orderId) => `/admin/orders/${orderId}`,
  ADMIN_ORDER_ACCEPT: (orderId) => `/admin/orders/${orderId}/accept`,
  ADMIN_ORDER_REJECT: (orderId) => `/admin/orders/${orderId}/reject`,
  ADMIN_ORDER_COMPLETE: (orderId) => `/admin/orders/${orderId}/complete`,
  ADMIN_ORDER_CANCEL: (orderId) => `/admin/orders/${orderId}/cancel`,
  ADMIN_MANUAL_SALES: '/admin/manual-sales',
  ADMIN_WEEKLY_REPORTS: '/admin/reports/weekly',
  ADMIN_WEEKLY_REPORT_PERSISTED_PDF: (reportId) => `/admin/reports/weekly/${reportId}/pdf`,
  ADMIN_WEEKLY_REPORT_SUMMARY: '/admin/reports/weekly/summary',
  ADMIN_WEEKLY_REPORT_PDF: '/admin/reports/weekly/pdf'
};
